name: Continuous Deployment for main release
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.MAINPASSWORD }}
          host: ${{ secrets.MAINHOST }}
          username: ${{ secrets.MAINUSERNAME }}
          port: ${{ secrets.MAINPORT }}
          script: |
            sh ~/autoCD.sh 2>&1
